<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test Report</title>
    <style>body {
  font-family: Helvetica, Arial, sans-serif;
  font-size: 12px;
  /* do not increase min-width as some may use split screens */
  min-width: 800px;
  color: #999;
}

h1 {
  font-size: 24px;
  color: black;
}

h2 {
  font-size: 16px;
  color: black;
}

p {
  color: black;
}

a {
  color: #999;
}

table {
  border-collapse: collapse;
}

/******************************
 * SUMMARY INFORMATION
 ******************************/
#environment td {
  padding: 5px;
  border: 1px solid #E6E6E6;
}
#environment tr:nth-child(odd) {
  background-color: #f6f6f6;
}

/******************************
 * TEST RESULT COLORS
 ******************************/
span.passed,
.passed .col-result {
  color: green;
}

span.skipped,
span.xfailed,
span.rerun,
.skipped .col-result,
.xfailed .col-result,
.rerun .col-result {
  color: orange;
}

span.error,
span.failed,
span.xpassed,
.error .col-result,
.failed .col-result,
.xpassed .col-result {
  color: red;
}

/******************************
 * RESULTS TABLE
 *
 * 1. Table Layout
 * 2. Extra
 * 3. Sorting items
 *
 ******************************/
/*------------------
 * 1. Table Layout
 *------------------*/
#results-table {
  border: 1px solid #e6e6e6;
  color: #999;
  font-size: 12px;
  width: 100%;
}
#results-table th,
#results-table td {
  padding: 5px;
  border: 1px solid #E6E6E6;
  text-align: left;
}
#results-table th {
  font-weight: bold;
}

/*------------------
 * 2. Extra
 *------------------*/
.log {
  background-color: #e6e6e6;
  border: 1px solid #e6e6e6;
  color: black;
  display: block;
  font-family: "Courier New", Courier, monospace;
  height: 230px;
  overflow-y: scroll;
  padding: 5px;
  white-space: pre-wrap;
}
.log:only-child {
  height: inherit;
}

div.image {
  border: 1px solid #e6e6e6;
  float: right;
  height: 240px;
  margin-left: 5px;
  overflow: hidden;
  width: 320px;
}
div.image img {
  width: 320px;
}

div.video {
  border: 1px solid #e6e6e6;
  float: right;
  height: 240px;
  margin-left: 5px;
  overflow: hidden;
  width: 320px;
}
div.video video {
  overflow: hidden;
  width: 320px;
  height: 240px;
}

.collapsed {
  display: none;
}

.expander::after {
  content: " (show details)";
  color: #BBB;
  font-style: italic;
  cursor: pointer;
}

.collapser::after {
  content: " (hide details)";
  color: #BBB;
  font-style: italic;
  cursor: pointer;
}

/*------------------
 * 3. Sorting items
 *------------------*/
.sortable {
  cursor: pointer;
}

.sort-icon {
  font-size: 0px;
  float: left;
  margin-right: 5px;
  margin-top: 5px;
  /*triangle*/
  width: 0;
  height: 0;
  border-left: 8px solid transparent;
  border-right: 8px solid transparent;
}
.inactive .sort-icon {
  /*finish triangle*/
  border-top: 8px solid #E6E6E6;
}
.asc.active .sort-icon {
  /*finish triangle*/
  border-bottom: 8px solid #999;
}
.desc.active .sort-icon {
  /*finish triangle*/
  border-top: 8px solid #999;
}
</style></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++)
        filterItems[i].hidden = false;
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>report.html</h1>
    <p>Report generated on 24-Feb-2021 at 14:12:31 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.1.1</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>JAVA_HOME</td>
        <td>C:\Program Files\Java\jdk1.8.0_211</td></tr>
      <tr>
        <td>Packages</td>
        <td>{"pluggy": "0.13.1", "py": "1.10.0", "pytest": "6.2.1"}</td></tr>
      <tr>
        <td>Platform</td>
        <td>Windows-7-6.1.7601-SP1</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"forked": "1.3.0", "html": "3.1.1", "metadata": "1.11.0", "pytest_check": "1.0.1", "rerunfailures": "9.1.1", "xdist": "2.2.0"}</td></tr>
      <tr>
        <td>Python</td>
        <td>3.8.5</td></tr></table>
    <h2>Summary</h2>
    <p>6 tests ran in 109.61 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">0 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">6 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>, <input checked="true" class="filter" data-test-result="rerun" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="rerun">18 rerun</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data0]</td>
          <td class="col-duration">3.31</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;10001&#x27;, &#x27;data&#x27;: None, &#x27;msg&#x27;: &#x27;充值成功&#x27;, &#x27;status&#x27;: 1}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;p...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506310&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045068E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553A00&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553DC0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506CD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D9A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045539A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data1]</td>
          <td class="col-duration">5.14</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20109&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;手机号码格式不正确&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;,...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;1806666888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFA0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0580&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A07C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0B20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553C10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0610&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A09D0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data2]</td>
          <td class="col-duration">3.53</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20103&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;参数错误：参数不能为空&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}, &#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D5E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DC10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0CD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553D60&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD1C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D0D0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0D00&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data3]</td>
          <td class="col-duration">3.73</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20104&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;此手机号对应的会员不存在&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E23A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD760&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A02E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A03D0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4EE0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BDA30&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data4]</td>
          <td class="col-duration">3.71</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;请输入金额&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pw...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: None, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2400&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD1C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BDA90&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C99D0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E27F0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4580&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045538B0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0940&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047D57F0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047D5E80&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047D5910&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data5]</td>
          <td class="col-duration">5.27</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;输入金额的金额小数不能超过两位&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666...hdata&#x27;: {&#x27;amount&#x27;: 9890.789, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000036E25B0&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E25E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E29A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4C10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9B80&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9F70&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047DE160&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047D5880&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047D5160&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C98E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553910&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data0]</td>
          <td class="col-duration">4.94</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;10001&#x27;, &#x27;data&#x27;: None, &#x27;msg&#x27;: &#x27;充值成功&#x27;, &#x27;status&#x27;: 1}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;p...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506310&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045068E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data0]</td>
          <td class="col-duration">3.82</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;10001&#x27;, &#x27;data&#x27;: None, &#x27;msg&#x27;: &#x27;充值成功&#x27;, &#x27;status&#x27;: 1}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;p...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506310&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045068E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553A00&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553DC0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506CD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data0]</td>
          <td class="col-duration">3.34</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;10001&#x27;, &#x27;data&#x27;: None, &#x27;msg&#x27;: &#x27;充值成功&#x27;, &#x27;status&#x27;: 1}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;p...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506310&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045068E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553A00&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553DC0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004506CD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D9A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data1]</td>
          <td class="col-duration">5.26</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20109&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;手机号码格式不正确&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;,...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;1806666888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFA0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0580&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data1]</td>
          <td class="col-duration">4.73</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20109&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;手机号码格式不正确&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;,...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;1806666888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFA0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0580&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A07C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0B20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data1]</td>
          <td class="col-duration">5.15</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20109&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;手机号码格式不正确&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;,...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;1806666888&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFA0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D190&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0580&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DFD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A07C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0B20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553C10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0610&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data2]</td>
          <td class="col-duration">4.58</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20103&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;参数错误：参数不能为空&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}, &#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D5E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data2]</td>
          <td class="col-duration">5.39</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20103&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;参数错误：参数不能为空&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}, &#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D5E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DC10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0CD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data2]</td>
          <td class="col-duration">4.26</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20103&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;参数错误：参数不能为空&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}, &#x27;rechdata&#x27;: {&#x27;amount&#x27;: 10000}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D5E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478D130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x000000000478DC10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0CD0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x0000000004553D60&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD1C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data3]</td>
          <td class="col-duration">4.30</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20104&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;此手机号对应的会员不存在&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E23A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD760&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data3]</td>
          <td class="col-duration">3.43</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20104&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;此手机号对应的会员不存在&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E23A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD760&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data3]</td>
          <td class="col-duration">4.22</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20104&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;此手机号对应的会员不存在&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666888...rechdata&#x27;: {&#x27;amount&#x27;: 10000, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E23A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD760&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD430&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2130&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4820&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A02E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 10000}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0790&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data4]</td>
          <td class="col-duration">9.87</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;请输入金额&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pw...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: None, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2400&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD1C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BDA90&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data4]</td>
          <td class="col-duration">3.86</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;请输入金额&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pw...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: None, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2400&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD1C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BDA90&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C99D0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E27F0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data4]</td>
          <td class="col-duration">3.88</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;请输入金额&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pw...&#x27;rechdata&#x27;: {&#x27;amount&#x27;: None, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E2400&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BD1C0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047BDA90&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C99D0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9E20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E27F0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4580&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000045538B0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: None}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0940&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data5]</td>
          <td class="col-duration">3.91</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;输入金额的金额小数不能超过两位&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666...hdata&#x27;: {&#x27;amount&#x27;: 9890.789, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000044FA490&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E25E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data5]</td>
          <td class="col-duration">4.80</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;输入金额的金额小数不能超过两位&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666...hdata&#x27;: {&#x27;amount&#x27;: 9890.789, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000045060A0&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E25E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E29A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4C10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9B80&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="rerun results-table-row">
        <tr>
          <td class="col-result">Rerun</td>
          <td class="col-name">zonghe/test_script/test_recharge.py::test_recharge[recharge_data5]</td>
          <td class="col-duration">3.80</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">recharge_data = {&#x27;expect&#x27;: {&#x27;code&#x27;: &#x27;20115&#x27;, &#x27;data&#x27;: {}, &#x27;msg&#x27;: &#x27;输入金额的金额小数不能超过两位&#x27;, &#x27;status&#x27;: 0}, &#x27;logindata&#x27;: {&#x27;mobilephone&#x27;: &#x27;1806666...hdata&#x27;: {&#x27;amount&#x27;: 9890.789, &#x27;mobilephone&#x27;: &#x27;18066668890&#x27;}, &#x27;regdata&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}<br/>baserequest = &lt;zonghe.caw.BaseRequests.BaseRequests object at 0x00000000047D5760&gt;<br/>url = &#x27;http://192.168.1.64:8089/&#x27;<br/>db_info = {&#x27;host&#x27;: &#x27;192.168.1.64&#x27;, &#x27;name&#x27;: &#x27;apple&#x27;, &#x27;port&#x27;: 3306, &#x27;pwd&#x27;: &#x27;123456&#x27;, ...}<br/><br/>    def test_recharge(recharge_data,baserequest,url,db_info):<br/>        # 注册用户<br/>        MySqlOp.delete_user(db_info,recharge_data[&#x27;regdata&#x27;][&#x27;mobilephone&#x27;])<br/>        Member.register(baserequest,url,recharge_data[&#x27;regdata&#x27;])<br/>        # 登录用户<br/>        Member.login(baserequest,url,recharge_data[&#x27;logindata&#x27;])<br/>        # 充值<br/>        r = Member.recharge(baserequest,url,recharge_data[&#x27;rechdata&#x27;])<br/>        # 校验结果<br/>&gt;       Check.equal(r.json(),recharge_data[&#x27;expect&#x27;],&#x27;code,status,msg&#x27;)<br/><span class="error">E       AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;json&#x27;</span><br/><br/>test_recharge.py:22: AttributeError<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E25E0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047A0C40&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9550&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036E29A0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000036D4C10&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9B80&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/> ------------------------------Captured stdout call------------------------------ <br/>连接数据库成功
执行sql语句成功
断开数据库连接成功
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/register,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047C9F70&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/login,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668888&#x27;, &#x27;pwd&#x27;: &#x27;abcd_1&#x27;}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/login (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047DE160&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
发送post请求，url:http://192.168.1.64:8089/futureloan/mvc/api/member/recharge,请求参数:{&#x27;data&#x27;: {&#x27;mobilephone&#x27;: &#x27;18066668890&#x27;, &#x27;amount&#x27;: 9890.789}}异常，异常信息为HTTPConnectionPool(host=&#x27;192.168.1.64&#x27;, port=8089): Max retries exceeded with url: /futureloan/mvc/api/member/recharge (Caused by NewConnectionError(&#x27;&lt;urllib3.connection.HTTPConnection object at 0x00000000047D5880&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。&#x27;))
<br/></div></td></tr></tbody></table></body></html>